import {
    getNamedType,
    isEnumType,
    isInterfaceType,
    isInputObjectType,
    isListType,
    isNonNullType,
    isObjectType,
    isScalarType,
    isUnionType,
    type GraphQLNamedType,
    type GraphQLSchema,
    type GraphQLType
} from 'graphql';

function safePropKey(key: string): string {
    return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : JSON.stringify(key);
}

export function unwrapCollectionElementType(fieldType: GraphQLType): GraphQLNamedType {
    // fieldType is usually [T!]! or [T!] etc. We want T.
    let t: GraphQLType = fieldType;
    while (isNonNullType(t)) t = t.ofType;
    if (isListType(t)) {
        t = t.ofType;
        while (isNonNullType(t)) t = t.ofType;
        return getNamedType(t);
    }
    return getNamedType(t);
}

export function collectReachableTypes(_schema: GraphQLSchema, roots: GraphQLNamedType[]): GraphQLNamedType[] {
    const queue: GraphQLNamedType[] = [...roots];
    const seen = new Set<string>();

    const add = (t: GraphQLNamedType) => {
        if (t.name.startsWith('__')) return;
        if (seen.has(t.name)) return;
        seen.add(t.name);
        queue.push(t);
    };

    for (const r of roots) {
        if (!r.name.startsWith('__')) seen.add(r.name);
    }

    const out: GraphQLNamedType[] = [];

    while (queue.length) {
        const t = queue.shift()!;
        out.push(t);

        if (isObjectType(t) || isInterfaceType(t)) {
            const fields = t.getFields();
            for (const field of Object.values(fields)) {
                const named = getNamedType(field.type);
                add(named);
            }
        } else if (isUnionType(t)) {
            for (const possible of t.getTypes()) add(possible);
        }
    }

    return out.sort((a, b) => a.name.localeCompare(b.name));
}

export function renderTsFromSchema(
    types: GraphQLNamedType[],
    options?: {
        scalars?: Record<string, string>;
        includeGraphqlTypeComments?: boolean;
        /**
         * When true (default), emit `export type ...` declarations.
         * When false, emit local `type ...` declarations.
         */
        exportTypes?: boolean;
    }
): string {
    const scalarMap: Record<string, string> = {
        ID: 'string',
        String: 'string',
        Boolean: 'boolean',
        Int: 'number',
        Float: 'number',
        json: 'any',
        jsonb: 'any',
        date: 'string',
        timestamptz: 'string',
        timestamp: 'string',
        uuid: 'string',
        ...(options?.scalars ?? {})
    };

    const renderGraphqlTypeRef = (t: GraphQLType): string => {
        if (isNonNullType(t)) return `${renderGraphqlTypeRef(t.ofType)}!`;
        if (isListType(t)) return `[${renderGraphqlTypeRef(t.ofType)}]`;
        return getNamedType(t).name;
    };

    const renderTypeRef = (t: GraphQLType): string => {
        if (!isNonNullType(t)) {
            return `${renderTypeRefNonNull(t)} | null`;
        }
        return renderTypeRefNonNull(t.ofType);
    };

    const renderTypeRefNonNull = (t: GraphQLType): string => {
        if (isNonNullType(t)) return renderTypeRefNonNull(t.ofType);
        if (isListType(t)) return `Array<${renderTypeRef(t.ofType)}>`;

        const named = getNamedType(t);
        if (isScalarType(named)) {
            return scalarMap[named.name] ?? 'unknown';
        }
        return named.name;
    };

    const includeGraphqlTypeComments = options?.includeGraphqlTypeComments === true;
    const exportTypes = options?.exportTypes !== false;
    const typePrefix = exportTypes ? 'export type' : 'type';

    const chunks: string[] = [];
    chunks.push('/* eslint-disable @typescript-eslint/no-unused-vars */');
    chunks.push('// This file is auto-generated by `dtv typegen`.');
    chunks.push('// Do not edit manually.');
    chunks.push('');

    for (const t of types) {
        const typeName = t.name;
        if (t.name.startsWith('__')) continue;

        if (isScalarType(t)) {
            continue;
        }

        if (isEnumType(t)) {
            const values = t.getValues().map(v => JSON.stringify(v.name)).join(' | ');
            chunks.push(`${typePrefix} ${typeName} = ${values || 'never'};`);
            chunks.push('');
            continue;
        }

        if (isUnionType(t)) {
            const members = t.getTypes().map(m => m.name).join(' | ');
            chunks.push(`${typePrefix} ${typeName} = ${members || 'never'};`);
            chunks.push('');
            continue;
        }

        if (isObjectType(t) || isInterfaceType(t)) {
            const fields = t.getFields();
            const lines: string[] = [];
            for (const field of Object.values(fields)) {
                if (field.name.startsWith('__')) continue;
                const key = safePropKey(field.name);
                const tsType = renderTypeRef(field.type);
                if (includeGraphqlTypeComments) {
                    lines.push(`    ${key}: ${tsType}; // GraphQL: ${renderGraphqlTypeRef(field.type)}`);
                } else {
                    lines.push(`    ${key}: ${tsType};`);
                }
            }
            chunks.push(`${typePrefix} ${typeName} = {`);
            chunks.push(...lines);
            chunks.push('};');
            chunks.push('');
            continue;
        }

        if (isInputObjectType(t)) {
            // Not expected in reachable output types, but keep deterministic behavior.
            const fields = t.getFields();
            const lines: string[] = [];
            for (const field of Object.values(fields)) {
                const key = safePropKey(field.name);
                const tsType = renderTypeRef(field.type);
                if (includeGraphqlTypeComments) {
                    lines.push(`    ${key}: ${tsType}; // GraphQL: ${renderGraphqlTypeRef(field.type)}`);
                } else {
                    lines.push(`    ${key}: ${tsType};`);
                }
            }
            chunks.push(`${typePrefix} ${typeName} = {`);
            chunks.push(...lines);
            chunks.push('};');
            chunks.push('');
            continue;
        }

        chunks.push(`${typePrefix} ${typeName} = unknown;`);
        chunks.push('');
    }

    return chunks.join('\n');
}
